# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/636e2f55-6c8e-48b4-8fda-05095668387d";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/636e2f55-6c8e-48b4-8fda-05095668387d";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/636e2f55-6c8e-48b4-8fda-05095668387d";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/home/yz/Games" =
    { device = "/dev/disk/by-uuid/636e2f55-6c8e-48b4-8fda-05095668387d";
      fsType = "btrfs";
      options = [ "subvol=@games" "nodatacow" "noatime" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/636e2f55-6c8e-48b4-8fda-05095668387d";
      fsType = "btrfs";
      options = [ "subvol=@swap" "nodatacow" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1070-A465";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
